# Generated by Django 5.1.2 on 2024-11-03 05:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="taskname",
            new_name="title",
        ),
    ]
