# Generated by Django 5.1.2 on 2024-12-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userapp", "0004_plantlist_delete_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="PlantList",
        ),
    ]
